FROM eclipse-temurin:17-jdk-jammy as builder

USER root

WORKDIR /opt/app
COPY .mvn/ .mvn
COPY mvnw pom.xml ./

COPY ./src ./src
RUN ./mvnw clean install
 
FROM eclipse-temurin:17-jre-jammy

WORKDIR /opt/app


EXPOSE 8080

COPY --from=builder /opt/app/target/*.jar /opt/app/*.jar

RUN chgrp -R 0 /opt/app && \
    chmod -R g=u /opt/app

USER 1001

ENTRYPOINT ["java","-jar", "/opt/app/*.jar"]
